### ISSUE TITLE
let block example in docs is erroring -- remove outdated examples and test examples during doc build

### ISSUE THREAD

**Issue by filchristou** [JuliaDynamics/ResumableFunctions.jl#125]
The example in the docs https://juliadynamics.github.io/ResumableFunctions.jl/stable/manual/#Let-block is erroring although it appears working in the docs.

```julia
julia> @resumable function arrays_of_tuples()
         for u in [[(1,2),(3,4)], [(5,6),(7,8)]]
           for i in 1:2
             let i=i
        val = [a[i] for a in u]
             end
             @yield val
           end
         end
       end
arrays_of_tuples (generic function with 1 method)

julia> for array in arrays_of_tuples() println(array) end
ERROR: UndefVarError: `val` not defined in `Main`
Suggestion: check for spelling errors or missing imports.
Stacktrace:
 [1] macro expansion
   @ ~/.julia/packages/ResumableFunctions/qmUpa/src/transforms.jl:250 [inlined]
 [2] (::var"##arrays_of_tuples_FSMI#367"{…})(_arg::Nothing)
   @ Main ~/.julia/packages/ResumableFunctions/qmUpa/src/macro.jl:110
 [3] ##arrays_of_tuples_FSMI#367
   @ ~/.julia/packages/ResumableFunctions/qmUpa/src/macro.jl:213 [inlined]
 [4] iterate (repeats 2 times)
   @ ~/.julia/packages/ResumableFunctions/qmUpa/src/types.jl:24 [inlined]
 [5] top-level scope
   @ ./REPL[48]:1
Some type information was truncated. Use `show(err)` to see complete types.
```

**Comment by Krastanov** [comment]
fixed by #130

**Comment by digital-carver** [comment]
#130 doesn't fix this, but I'll soon make a PR to address this. The title actually reminds me of another thing I wanted to do - the examples have a weird setup where instead of testing the examples themselves, the code is duplicated (sometimes imperfectly - which is partly what led to this issue), once in a doctest setup and once as an example block. I had planned to work on that anyway, so I'll remove this `let` block example when I make a PR for that.
